### PR TITLE
Add batching feature to bulk send log events

### PR DESCRIPTION
**Pull request by phawxby**
Currently log requests are sent individually. For high volume applications such as ours this results in significant amount request volume, this implements log batching to bundle together a bunch of log entries into a single POST. Also includes the fix for #16 & #17.

I've validated logging works correctly against our private NewRelic instance with the reworked pattern.
image

### CODE REVIEW

**Comment by phawxby** [comment]
@joaolrpaulo just following up on this one.

**Review by joaolrpaulo — APPROVED** [review]

**Comment by joaolrpaulo** [comment]
Sorry, for the delay. I will deploy these changes between tomorrow, does that fit your needs?

**Comment by phawxby** [comment]
> Sorry, for the delay. I will deploy these changes between tomorrow, does that fit your needs?

Sure, whatever schedule works for you. I actually now have the module directly in our deployed code-base for now as we needed to get it out. Thanks

**Comment by joaolrpaulo** [comment]
Published v1.3.0. (v1.2.0 skipped due to dumb CLI script run 🤦🏼‍♂️)

**Pull request merged**
